spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/mydb
    username: postgres
    password: admin
    driverClassName: org.postgresql.Driver
